language: java
sudo: false

after success:
    bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - mr.r.m3@icloud.com
    on_succes: never # default: change
    on_failure: always # default: always
